# GitLab CI/CD configuration for RTMS project

image: mcr.microsoft.com/dotnet/sdk:8.0  # Use the .NET 8.0 SDK image

variables:
  # Define paths specific to your projects
  CORE_BUSINESS_PROJECT: 'RTMS.CoreBusiness/RTMS.CoreBusiness.csproj'
  USE_CASES_PROJECT: 'RTMS.UseCases/RTMS.UseCases.csproj'
  WEBAPP_PROJECT: 'RTMS.Web/RTMS.Web.csproj'
  TEST_PROJECT: 'RTMS.Tests/RTMS.Tests.csproj'
  PLUGIN_PROJECT: 'RTMS.Plugins/RTMS.Plugins.PostgreEFCore/RTMS.Plugins.PostgreEFCore.csproj'
  EXE_RELEASE_FOLDER: 'RTMS.Web/bin/Release/net8.0'
  TEST_DLL: 'RTMS.Tests/bin/Release/net8.0/RTMS.Tests.dll'
  DEPLOY_FOLDER: 'P:\Projects\RTMS\Builds'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  only:
    - tags
  script:
    - 'dotnet restore'  # Restore NuGet packages for the entire solution
    - 'dotnet build $CORE_BUSINESS_PROJECT --configuration Release'
    - 'dotnet build $USE_CASES_PROJECT --configuration Release'
    - 'dotnet build $WEBAPP_PROJECT --configuration Release'
    - 'dotnet build $TEST_PROJECT --configuration Release'
    - 'dotnet build $PLUGIN_PROJECT --configuration Release'
  artifacts:
    expire_in: 1 week
    paths:
      - '$EXE_RELEASE_FOLDER/RTMS.Web.dll'
      - '$TEST_DLL'

test_job:
  stage: test
  only:
    - tags
  script:
    - 'dotnet tool install --global dotnet-xunit-cli'
    - 'dotnet xunit $TEST_DLL -xml TestResult.xml'
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - 'TestResult.xml'
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  only:
    - tags
  script:
    - 'apt-get update && apt-get install -y git'  # Install git for commit message
    - '$commitSubject = $(git log -1 --pretty=%s)'
    - '$deployFolder = "$DEPLOY_FOLDER/$CI_COMMIT_TAG - $commitSubject"'
    - 'mkdir -p "$deployFolder"'
    - 'cp "$EXE_RELEASE_FOLDER/RTMS.Web.dll" "$deployFolder/"'
    - 'cp "TestResult.xml" "$deployFolder/"'
  dependencies:
    - build_job
    - test_job
  environment: production