# GitLab CI/CD configuration for RTMS project

image: mcr.microsoft.com/dotnet/sdk:8.0  # Use the .NET 8.0 SDK image

variables:
  # Define paths specific to your projects
  CORE_BUSINESS_PROJECT: 'RTMS.CoreBusiness/RTMS.CoreBusiness.csproj'
  USE_CASES_PROJECT: 'RTMS.UseCases/RTMS.UseCases.csproj'
  WEBAPP_PROJECT: 'RTMS.Web/RTMS.Web.csproj'
  TEST_PROJECT: 'RTMS.Tests/RTMS.Tests.csproj'
  PLUGIN_PROJECT: 'RTMS.Plugins/RTMS.Plugins.PostgreEFCore/RTMS.Plugins.PostgreEFCore.csproj'
  EXE_RELEASE_FOLDER: 'RTMS.Web/bin/Release/net8.0'
  DEPLOY_FOLDER: 'P:\Projects\RTMS\Builds'

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  only:
    - tags
  script:
    - 'dotnet restore'  # Restore NuGet packages for the entire solution
    - 'dotnet build --configuration Release'  # Build all projects in the solution
  artifacts:
    expire_in: 1 week
    paths:
      - '*/bin/Release/net8.0/'

test_job:
  stage: test
  only:
    - tags
  script:
    - 'dotnet test $TEST_PROJECT --logger:"console;verbosity=detailed" --logger:"trx;LogFileName=TestResults.trx"'
  artifacts:
    when: always
    reports:
      junit: '**/TestResults.trx'
    expire_in: 1 week
    paths:
    - '**/TestResults.trx'
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  only:
    - tags
  script:
    - 'apt-get update && apt-get install -y git'  # Install git for commit message
    - 'commitSubject=$(git log -1 --pretty=%s)'
    - 'deployFolder="$DEPLOY_FOLDER/$CI_COMMIT_TAG - $commitSubject"'
    - 'mkdir -p "$deployFolder"'
    - 'cp "$EXE_RELEASE_FOLDER/RTMS.Web.dll" "$deployFolder/"'
    - 'cp "$CI_PROJECT_DIR/RTMS.Tests/TestResults/TestResults.trx" "$deployFolder/"'
  dependencies:
    - build_job
    - test_job
  environment: production